### ISSUE TITLE
what about ros2?

### ISSUE THREAD

**Issue by woodz-** [dheera/ros-pwm-pca9685#7]
Will this solution work for ros2 on catkin too? I see colcon dependencies in CMakeLists.txt which I guess points to old ros (version 1).

**Comment by BrettRD** [comment]
I'm not sure where I should put this to get it merged upstream
I ported this to ROS2, it nearly took a rewrite but it works basically the same.
https://github.com/BrettRD/ros-pwm-pca9685/tree/ros2

**Comment by woodz-** [comment]
Sorry, from what I understand today, I guess I've confused ros versions and their corresponding build tools.

What I know now is:

    ros1 <-> catkin
    ros2 <-> colcon

My original question pointed out:

    ros2 <-> catkin
    ros1 <-> colcon

whis is **not** a true assumption

I am going to close this confusion.
